# Generated by Django 4.2.7 on 2025-05-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VesselInfoFromCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrierCd', models.CharField(max_length=10, verbose_name='船公司')),
                ('polCd', models.CharField(max_length=10, verbose_name='起运港五字码')),
                ('podCd', models.CharField(max_length=10, verbose_name='目的港五字码')),
                ('vessel', models.CharField(max_length=100, verbose_name='船名')),
                ('voyage', models.CharField(max_length=50, verbose_name='航次')),
                ('gp_20', models.CharField(blank=True, max_length=50, null=True, verbose_name='20尺普通箱')),
                ('hq_40', models.CharField(blank=True, max_length=50, null=True, verbose_name='40尺高箱')),
                ('cut_off_time', models.CharField(blank=True, max_length=50, null=True, verbose_name='截关时间')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='价格')),
            ],
            options={
                'verbose_name': '船舶额外信息',
                'verbose_name_plural': '船舶额外信息',
                'db_table': 'vessel_info_from_company',
                'unique_together': {('carrierCd', 'polCd', 'podCd', 'vessel', 'voyage')},
            },
        ),
    ]
