# Generated by Django 4.2.7 on 2025-05-26 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_local_fee_models'),
        ('schedules', '0003_local_fee_models'),
    ]

    operations = [
    ]
