# Generated by Django 4.2.7 on 2025-05-26 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_merge_0002_local_fee_models_0003_local_fee_models'),
    ]

    operations = [
        # No operations needed - this is to resolve migration conflicts
    ]
