# Generated by Django 4.2.7 on 2025-06-06 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_auto_20250526_2345'),
    ]

    operations = [
    ]
