# Generated by Django 4.2.7 on 2025-05-26 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local_fees', '0002_add_localfeerate'),
        ('local_fees', '0002_localfeerate'),
    ]

    operations = [
    ]
