# Generated by Django - Sync model state without touching existing data
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('local_fees', '0004_add_new_fields_and_update_data'),
    ]

    operations = [
        # 同步unique_together约束 - 不修改数据，只同步模型状态
        migrations.AlterUniqueTogether(
            name='localfeerate',
            unique_together={('vessel', 'polCd', 'podCd', 'fee_type')},
        ),
    ]
