# Generated by Django 4.2.7 on 2025-06-06 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('local_fees', '0006_reset_to_simple_model'),
    ]

    operations = [
    ]
