# Generated by Django 4.2.7 on 2025-05-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='用户的邮箱地址，用于登录认证', max_length=255, unique=True, verbose_name='邮箱地址')),
                ('first_name', models.CharField(blank=True, help_text='用户的名字', max_length=30, verbose_name='名字')),
                ('last_name', models.CharField(blank=True, help_text='用户的姓氏', max_length=30, verbose_name='姓氏')),
                ('is_active', models.BooleanField(default=True, help_text='用户账户是否处于激活状态', verbose_name='是否激活')),
                ('is_staff', models.BooleanField(default=False, help_text='用户是否可以访问管理后台', verbose_name='是否为管理员')),
                ('date_joined', models.DateTimeField(auto_now_add=True, help_text='用户账户创建的时间', verbose_name='注册时间')),
                ('last_login', models.DateTimeField(blank=True, help_text='用户最后一次登录的时间', null=True, verbose_name='最后登录时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'auth_user',
                'ordering': ['-date_joined'],
            },
        ),
    ]
