# Generated by Django 4.2.7 on 2025-05-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='权限的唯一标识符，如 user.list, user.create', max_length=100, unique=True, verbose_name='权限代码')),
                ('name', models.CharField(help_text='权限的显示名称', max_length=100, verbose_name='权限名称')),
                ('description', models.TextField(blank=True, help_text='权限的详细描述', verbose_name='权限描述')),
                ('category', models.CharField(default='system', help_text='权限所属的功能模块分类', max_length=50, verbose_name='权限分类')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
                'db_table': 'auth_custom_permission',
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='角色的名称', max_length=50, unique=True, verbose_name='角色名称')),
                ('description', models.TextField(blank=True, help_text='角色的详细描述', verbose_name='角色描述')),
                ('is_active', models.BooleanField(default=True, help_text='角色是否处于激活状态', verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('permissions', models.ManyToManyField(blank=True, help_text='该角色拥有的权限', to='authentication.permission', verbose_name='权限')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'auth_role',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='用户拥有的角色', to='authentication.role', verbose_name='角色'),
        ),
    ]
