# Generated by Django 4.2.7 on 2025-05-24 01:30

from django.db import migrations


def create_vessel_info_permissions(apps, schema_editor):
    """
    创建船舶额外信息相关权限
    """
    Permission = apps.get_model('authentication', 'Permission')
    
    # 定义船舶额外信息权限数据
    vessel_info_permissions = [
        {
            'code': 'vessel_info.list',
            'name': '查看船舶额外信息列表',
            'description': '允许查看船舶额外信息列表',
            'category': '船舶信息管理'
        },
        {
            'code': 'vessel_info.detail',
            'name': '查看船舶额外信息详情',
            'description': '允许查看单个船舶额外信息的详细信息',
            'category': '船舶信息管理'
        },
        {
            'code': 'vessel_info.create',
            'name': '创建船舶额外信息',
            'description': '允许创建新的船舶额外信息记录',
            'category': '船舶信息管理'
        },
        {
            'code': 'vessel_info.update',
            'name': '修改船舶额外信息',
            'description': '允许修改船舶额外信息',
            'category': '船舶信息管理'
        },
        {
            'code': 'vessel_info.delete',
            'name': '删除船舶额外信息',
            'description': '允许删除船舶额外信息记录',
            'category': '船舶信息管理'
        },
    ]
    
    # 创建权限
    for perm_data in vessel_info_permissions:
        Permission.objects.get_or_create(
            code=perm_data['code'],
            defaults=perm_data
        )


def remove_vessel_info_permissions(apps, schema_editor):
    """
    删除船舶额外信息相关权限（回滚操作）
    """
    Permission = apps.get_model('authentication', 'Permission')
    
    vessel_info_permission_codes = [
        'vessel_info.list',
        'vessel_info.detail', 
        'vessel_info.create',
        'vessel_info.update',
        'vessel_info.delete',
    ]
    
    Permission.objects.filter(code__in=vessel_info_permission_codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20250523_2127'),
    ]

    operations = [
        migrations.RunPython(
            create_vessel_info_permissions,
            remove_vessel_info_permissions
        ),
    ] 