# Generated by Django 4.2.7 on 2025-05-24 01:35

from django.db import migrations


def update_vessel_info_category(apps, schema_editor):
    """
    更新船舶额外信息权限的分类为中文
    """
    Permission = apps.get_model('authentication', 'Permission')
    
    # 更新权限分类
    vessel_info_permission_codes = [
        'vessel_info.list',
        'vessel_info.detail', 
        'vessel_info.create',
        'vessel_info.update',
        'vessel_info.delete',
    ]
    
    Permission.objects.filter(code__in=vessel_info_permission_codes).update(
        category='船舶信息管理'
    )


def revert_vessel_info_category(apps, schema_editor):
    """
    回滚权限分类更新
    """
    Permission = apps.get_model('authentication', 'Permission')
    
    vessel_info_permission_codes = [
        'vessel_info.list',
        'vessel_info.detail', 
        'vessel_info.create',
        'vessel_info.update',
        'vessel_info.delete',
    ]
    
    Permission.objects.filter(code__in=vessel_info_permission_codes).update(
        category='vessel_info_management'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_add_vessel_info_permissions'),
    ]

    operations = [
        migrations.RunPython(
            update_vessel_info_category,
            revert_vessel_info_category
        ),
    ] 