# Generated by Django 4.2.7 on 2025-05-28 16:49

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_update_vessel_info_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text='用户头像图片', null=True, upload_to=authentication.models.user_avatar_upload_path, verbose_name='头像'),
        ),
    ]
